# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

name: $(Year:yyyy).$(Month)$(DayOfMonth)$(rev:.r)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- powershell: |
   Write-Host "Branch Name:"
   git checkout dev
- powershell: .\my-script.ps1
- script: dotnet build /home/vsts/work/1/s/VersionTest/VersionTest.sln
  displayName: 'dotnet build $(buildConfiguration)'
- powershell: |
   Write-Host "Branch Name:"
   git config --global url."git@github.com:halonazhao/versionAssemblies.git".insteadOf "https://github.com/"
   git config user.email zhao@janatechnology.com
   git config user.name "Version Updater"
   git add -A
   Write-Host "git commit with message"
   git commit -a -m "$(Build.BuildNumber)"
   Write-Host "git push"
   git push origin dev

